# Generated by Django 4.1 on 2022-11-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_customuser_company_name_customuser_union_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved_company_name',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_email',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_name',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_signature',
            field=models.ImageField(null=True, upload_to='user/documents'),
        ),
    ]
