# Generated by Django 4.1 on 2022-11-25 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_customuser_approved_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, null=True)),
                ('post', models.CharField(max_length=2000, null=True)),
                ('email', models.CharField(max_length=2000, null=True)),
                ('phone', models.CharField(max_length=2000, null=True)),
                ('image', models.ImageField(null=True, upload_to='user/teams')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
