deployment:
  tasks:
    # - export DEPLOYPATH=/home/radijmdg/fenfitnepal/ #this is demos
    - export DEPLOYPATH=/home/fenfitnepal/fenfitnepal/ #this is original
    - /bin/cp -r nepallocation $DEPLOYPATH
    - /bin/cp -r report $DEPLOYPATH
    - /bin/cp -r payment $DEPLOYPATH
    - /bin/cp -r Admin $DEPLOYPATH
    - /bin/cp -r account $DEPLOYPATH
    - /bin/cp -r media $DEPLOYPATH
  
