deployment:
  tasks:
    - export DEPLOYPATH=/home/royalretailshop/royal_family/
    - /bin/cp -r Ecommerce $DEPLOYPATH
    - /bin/cp -r Admin $DEPLOYPATH
    - /bin/cp -r account $DEPLOYPATH
    - /bin/cp -r media $DEPLOYPATH
  
  