# Generated by Django 4.1 on 2022-10-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CENTRAL'), (2, 'STATE'), (3, 'DISTRICT'), (4, 'USER')], null=True),
        ),
    ]
