# Generated by Django 4.1 on 2022-11-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district_name',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state_name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
