# Generated by Django 4.1 on 2022-11-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_applyForVerified',
            field=models.BooleanField(default=False),
        ),
    ]
