# Generated by Django 4.1 on 2022-11-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customuser_is_applyforverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.ImageField(null=True, upload_to='user/documents'),
        ),
    ]
