# Generated by Django 4.1 on 2022-11-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_customuser_member_admin_alter_teammember_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apply_role_type',
            field=models.IntegerField(null=True),
        ),
    ]
