# Generated by Django 4.1 on 2022-12-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_customuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division_forest_email',
            field=models.CharField(max_length=205, null=True),
        ),
    ]
