# Generated by Django 4.1 on 2022-11-01 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('discription', models.TextField(max_length=5000, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('banner_image', models.ImageField(null=True, upload_to='blogs/banner')),
                ('icon_image', models.ImageField(null=True, upload_to='blogs/icon')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
                ('read_unread', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_name_nepali', models.CharField(max_length=255, null=True)),
                ('site_email', models.EmailField(max_length=254)),
                ('site_contact', models.BigIntegerField()),
                ('site_contact_nepali', models.BigIntegerField(null=True)),
                ('site_address', models.CharField(max_length=255)),
                ('site_address_nepali', models.CharField(max_length=255, null=True)),
                ('fb_link', models.CharField(max_length=255, null=True)),
                ('twitter_link', models.CharField(max_length=255, null=True)),
                ('linkedin_link', models.CharField(max_length=255, null=True)),
                ('other_link', models.CharField(max_length=255, null=True)),
                ('page_title', models.CharField(max_length=255)),
                ('page_keyword', models.CharField(max_length=200, null=True)),
                ('page_discription', models.TextField(max_length=5000, null=True)),
                ('image1', models.ImageField(null=True, upload_to='global/fav_ico')),
                ('image2', models.ImageField(null=True, upload_to='global/logo')),
                ('image3', models.ImageField(null=True, upload_to='global/footer_logo')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255, null=True)),
                ('long_contents', models.TextField(max_length=255, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to='founders/')),
            ],
        ),
        migrations.CreateModel(
            name='UserApplicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('owner_full_name', models.CharField(max_length=205)),
                ('business_name', models.CharField(max_length=205, null=True)),
                ('municipality', models.CharField(max_length=205, null=True)),
                ('ward_number', models.CharField(max_length=205, null=True)),
                ('tole', models.CharField(default=None, max_length=205)),
                ('phone', models.CharField(max_length=205)),
                ('email', models.CharField(max_length=205)),
                ('district', models.CharField(max_length=300, null=True)),
                ('state', models.CharField(max_length=300, null=True)),
                ('certificate_citizenship', models.ImageField(null=True, upload_to='user/documents')),
                ('certificate_company_registration', models.ImageField(null=True, upload_to='user/documents')),
                ('provisional_account_number', models.ImageField(null=True, upload_to='user/documents')),
                ('auditing', models.ImageField(null=True, upload_to='user/documents')),
                ('tax_paid_certificate', models.ImageField(null=True, upload_to='user/documents')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_page_id', models.IntegerField(default=0)),
                ('caption', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('page_type', models.CharField(default=False, max_length=255)),
                ('title', models.CharField(max_length=500, null=True)),
                ('short_description', models.CharField(max_length=3000, null=True)),
                ('long_contents', models.TextField(max_length=255, null=True)),
                ('meta_title', models.CharField(max_length=255, null=True)),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('position', models.IntegerField()),
                ('banner_image1', models.ImageField(null=True, upload_to='navigation/banner1')),
                ('banner_image2', models.ImageField(null=True, upload_to='navigation/banner2')),
                ('icon_image', models.ImageField(null=True, upload_to='navigation/icon')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='Admin.navigation')),
            ],
        ),
        migrations.CreateModel(
            name='HomeNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_page_id', models.IntegerField(default=0)),
                ('caption', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('page_type', models.CharField(default=False, max_length=255)),
                ('title', models.CharField(max_length=500, null=True)),
                ('short_description', models.CharField(max_length=3000, null=True)),
                ('long_contents', models.TextField(max_length=255, null=True)),
                ('meta_title', models.CharField(max_length=255, null=True)),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('position', models.IntegerField()),
                ('banner_image1', models.ImageField(null=True, upload_to='home/banner1')),
                ('banner_image2', models.ImageField(null=True, upload_to='home/banner2')),
                ('icon_image', models.ImageField(null=True, upload_to='home/icon')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='Admin.homenavigation')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('get_user_application_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationform', to='Admin.userapplicationdetail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationform', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
