# Generated by Django 4.1 on 2022-11-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplicationdetail',
            name='tole',
            field=models.CharField(default=True, max_length=205),
        ),
    ]
