# Generated by Django 4.1 on 2022-11-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_applicationformcancelleddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='dsc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
