# Generated by Django 4.1 on 2022-11-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_states_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='state_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
