# Generated by Django 4.1 on 2022-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_states_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='state_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
