# Generated by Django 4.1 on 2022-11-08 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0012_alter_states_state_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='userapplicationdetail',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='bank_voucher',
            field=models.ImageField(null=True, upload_to='user/documents'),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='income_certificate',
            field=models.ImageField(null=True, upload_to='user/documents'),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='industry_registration',
            field=models.ImageField(null=True, upload_to='user/documents'),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='member_approved_certificate',
            field=models.ImageField(null=True, upload_to='user/documents'),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='self_declaration_not_on_the_black_list',
            field=models.ImageField(null=True, upload_to='user/documents'),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationdetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
