# Generated by Django 4.1 on 2022-11-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_businesstype_remove_userapplicationdetail_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendationPriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='business_price_category',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='voucher_number',
            field=models.CharField(max_length=505, null=True),
        ),
    ]
