# Generated by Django 4.1 on 2022-11-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_recomendationpricecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplicationdetail',
            name='is_payment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
