# Generated by Django 4.1 on 2022-11-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_userapplicationdetail_is_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplicationdetail',
            name='is_payment',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='is_payment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
