# Generated by Django 4.1 on 2022-11-18 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0016_remove_userapplicationdetail_is_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='is_payment',
        ),
        migrations.RemoveField(
            model_name='userapplicationdetail',
            name='district',
        ),
        migrations.RemoveField(
            model_name='userapplicationdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userapplicationdetail',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userapplicationdetail',
            name='state',
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='authorized_capital_of_company',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='company_name',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='is_reniew',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='number_of_employees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='paid_up_capital_of_company',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='payment_rupees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='tax_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='transaction_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='union_name',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='union_type',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='UserApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=205, null=True)),
                ('email', models.CharField(max_length=205, null=True)),
                ('owner_full_name', models.CharField(max_length=205, null=True)),
                ('company_name', models.CharField(max_length=205, null=True)),
                ('business_name', models.CharField(max_length=205, null=True)),
                ('business_price_category', models.CharField(max_length=205, null=True)),
                ('voucher_number', models.CharField(max_length=505, null=True)),
                ('is_payment', models.BooleanField(default=False, null=True)),
                ('is_renew', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('get_user_application_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='Admin.userapplicationdetail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to=settings.AUTH_USER_MODEL)),
                ('user_application_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='Admin.applicationform')),
            ],
        ),
    ]
