# Generated by Django 4.1 on 2022-11-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_alter_applicationform_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplicationdetail',
            name='approved_company_name',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='approved_email',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='approved_name',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='approved_signature',
            field=models.ImageField(null=True, upload_to='user/documents'),
        ),
    ]
