# Generated by Django 4.1 on 2022-11-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_userapplicationdetail_approved_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='is_payment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationpayment',
            name='payment_rupees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userapplicationpayment',
            name='who_payment',
            field=models.CharField(max_length=205, null=True),
        ),
    ]
