# Generated by Django 4.1 on 2022-11-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_applicationform_is_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='bill_number',
            field=models.CharField(max_length=205, null=True),
        ),
        migrations.AddField(
            model_name='userapplicationpayment',
            name='bill_number',
            field=models.CharField(max_length=205, null=True),
        ),
    ]
