# Generated by Django 4.1 on 2022-11-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_applicationform_bill_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='bill_number',
            field=models.CharField(default='', max_length=205),
        ),
    ]
