# Generated by Django 4.1 on 2022-11-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_applicationform_type_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplicationdetail',
            name='physical_year',
            field=models.CharField(max_length=205, null=True),
        ),
    ]
