# Generated by Django 4.1 on 2022-12-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_userapplicationdetail_physical_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapplicationdetail',
            old_name='industry_certificate',
            new_name='industry_certificate_back_side',
        ),
        migrations.AddField(
            model_name='userapplicationdetail',
            name='industry_certificate_front_side',
            field=models.ImageField(null=True, upload_to='user/documents'),
        ),
    ]
