# Generated by Django 4.1 on 2022-11-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nepallocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='nepallocation.states'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='district_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='municipality_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='states',
            name='province_id',
            field=models.IntegerField(null=True),
        ),
    ]
